export const influencers = [
  {
    id: '1',
    name: 'Mina Rivera',
    handle: '@minarivera',
    platform: 'Instagram',
    followers: '1.2M',
    engagement: '7.8%',
    category: 'Lifestyle',
    country: 'US',
    status: 'Active',
    profileImage: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=240&q=80',
  },
  {
    id: '2',
    name: 'Kai Chen',
    handle: '@kaichen',
    platform: 'TikTok',
    followers: '890K',
    engagement: '9.1%',
    category: 'Tech',
    country: 'SG',
    status: 'Review',
    profileImage: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=240&q=80',
  },
  {
    id: '3',
    name: 'Lina Santos',
    handle: '@linasantos',
    platform: 'YouTube',
    followers: '640K',
    engagement: '6.4%',
    category: 'Travel',
    country: 'BR',
    status: 'Active',
    profileImage: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=240&q=80',
  },
]
